// <auto-generated />
namespace SaveMeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOthertobool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOthertobool));
        
        string IMigrationMetadata.Id
        {
            get { return "201703221814312_AddOthertobool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
